#!/bin/bash

entries="自选截图到剪贴板\n全屏截图到剪贴板"

selected=$(printf "%b" "$entries" |
  wofi --dmenu \
    --cache-file /dev/null \
    --width 250 \
    --height 320 \
    --prompt "截图菜单" \
    --style ~/.config/wofi/style.css)

case "$selected" in
自选截图到剪贴板)
  hyprctl eval 'hl.config({ animations = { enabled = false } })' && grim -g "$(slurp)" - | wl-copy && hyprctl eval 'hl.config({ animations = { enabled = true } })'
  ;;
全屏截图到剪贴板)
  hyprctl eval 'hl.config({ animations = { enabled = false } })' && grim - | wl-copy && hyprctl eval 'hl.config({ animations = { enabled = true } })'
  ;;
esac
