##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
#windowrule = suppressevent maximize, class:.*
windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

# Fix some dragging issues with XWayland
#windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
  name = waypaper-float
  match:class = waypaper
  size = 800 500
  float = true
  center = on
}
windowrule {
  name = spotify-float
  match:class = Spotify
  size = 800 500
  float = true
  center = on
}

windowrule {
  name = clash-float
  match:class = com.follow.clash
  size = 1000 750
  float = true
  center = on
}

windowrule {
  name = bilibili-float
  match:class = bilibili
  size = 1200 800
  float = true
  center = on
}

windowrule {
  name = fdm-float
  match:class = fdm
  size = 800 600
  float = true
  center = on
}

windowrule {
  name = lutris-float
  match:class = net.lutris.Lutris
  size = 1200 800
  float = true
  center = on
}

windowrule {
  name = copyq-float
  match:class = com.github.hluk.copyq
  size = 800 500
  float = true
  center = on
}

windowrule {
  name = wechat-media
  match:class = wechat
  match:title = 图片和视频
  size = 800 500
  float = true
  center = on
}


windowrule {
  name = wechat-vid-cha
  match:class = wechat
  match:title = 视频聊天
  float = true
  center = on
}

windowrule {
  name = wechat-voc-cha
  match:class = wechat
  match:title = 语音聊天
  float = true
  center = on
}

windowrule {
  name = qq-viewer
  match:class = QQ
  match:title = 图片查看器
  size = 600 450
  float = true
  center = on
}

windowrule {
  name = waydroid-float
  match:class = Waydroid
  size = 1200 750
  float = true
  center = on
}

windowrule {
  name = mpv-opacity
  match:class = ^(mpv)$
  opacity = 1.0 override 1.0 override
}

windowrule {
  name = bilibili-opacity
  match:class = ^(bilibili)$
  opacity = 1.0 override 1.0 override
}

#windowrule {
 # name = fix-xwayland
 # match:xwayland = 1
 # border_size = 0
 # no_blur = on
 # no_shadow = on
#}

windowrule {
 name = hoi4-fullscreen
 match:class = hoi4
 fullscreen = true
}

